#数据库连接池以及mybatis框架配置项
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meteorologicalinfo?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: "root"
    password: "00000."
  mail:
    host: "smtp-relay.brevo.com"
    port: 587
    username: "xiaom9853@gmail.com"
    password: "h9FqM3IdzY7GSwfC"


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shen.meteManagerbackend.entity
  configuration:
    map-underscore-to-camel-case: true
# 日志权限
logging:
  level:
    com.shen.meteManagerbackend.dao: debug
# 高德开放天气查询API
lbs:
  key: "04c5f954f8d74eebcbccf93b0a4efe1e"

